rabbitmq-ha:
  enabled: true
  replicaCount: 1
  rbac:
    create: false
  persistence:
    enabled: false
    size: 3Gi

persistence:
  enabled: true
  efs:
    enabled: false
    dns: fs-example.efs.us-east-1.amazonaws.com #For aws you will need to specify the EFS server
    path: "/"
  baseSize: 20Gi

activemq:
  enabled: true
  
nginx-ingress:
  controller:
    scope:
      enabled: true

alfresco-activiti-cloud-registry:
  enabled: true
  nginx-ingress:
    enabled: false
alfresco-api-gateway:
  enabled: true
alfresco-identity-service:
  enabled: true
  keycloak:
    postgresql:
      persistence:
        existingClaim: "alfresco-volume-claim"
        subPath: "alfresco-identity-service/database-data"