apiVersion: v1
description: A Helm chart Providing the required Alfresco infrastructure for the Digital Business Platform. This includes activemq, alfresco-identity-service, nginx-ingress and a persistent volume to use with the DBP chart.
name: alfresco-infrastructure
version: 5.0.0
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
