dependencies:
  - name: activemq
    version: ^1.1.1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-infrastructure.activemq.enabled
  - name: alfresco-identity-service
    version: 1.1.0
    condition: alfresco-infrastructure.alfresco-identity-service.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: nginx-ingress
    condition: alfresco-infrastructure.nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.14.0
    